AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'
Parameters:
  paramBucketPrefixList:
    Description: Bucket Name Prefix
    Type: CommaDelimitedList
    Default: 's3testcaaa01,s3testcaaa02'
Resources:
  Fn::ForEach::BucketPrefix1st:
    - BucketPrefix
    - !Ref paramBucketPrefixList
    - ${BucketPrefix}:
        Type: 'AWS::S3::Bucket'
        Properties:
          BucketName: !Sub ${BucketPrefix}-${AWS::AccountId}
    - BucketPrefix1st: !Join ["bbb", !Split ["aaa", BucketPrefix1st]]